# Generated by Django 2.2 on 2019-06-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rc_number',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
    ]
