# Generated by Django 2.2 on 2019-06-05 03:39

from django.db import migrations, models
import django_thumbs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20190604_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='Enter Company Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=django_thumbs.fields.ImageThumbsField(blank=True, default=None, null=True, sizes=({'code': '60x60', 'resize': 'crop', 'wxh': '60x60'}, {'code': '100x100', 'resize': 'crop', 'wxh': '100x100'}, {'code': '200x200', 'resize': 'crop', 'wxh': '200x200'}, {'code': '400x400', 'resize': 'crop', 'wxh': '400x400'}), upload_to='photos/'),
        ),
    ]
