# Generated by Django 2.2 on 2019-06-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20190605_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
    ]
