# Generated by Django 2.2 on 2019-06-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20190605_0440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cover',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
