# Generated by Django 2.2 on 2019-06-05 06:23

from django.db import migrations
import django_thumbs.fields
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20190605_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cover',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=django_thumbs.fields.ImageThumbsField(blank=True, default=None, null=True, sizes=({'code': '60x60', 'resize': 'crop', 'wxh': '60x60'}, {'code': '100x100', 'resize': 'crop', 'wxh': '100x100'}, {'code': '200x200', 'resize': 'crop', 'wxh': '200x200'}, {'code': '400x400', 'resize': 'crop', 'wxh': '400x400'}), upload_to=user_profile.models.upload_avatar_to),
        ),
    ]
