# Generated by Django 2.2 on 2019-06-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20190605_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plans',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reg_status',
            field=models.IntegerField(default=0),
        ),
    ]
